### ISSUE TITLE
Multilingual menu not working

### ISSUE THREAD

**Issue by lupa18** [themefisher/meghna-hugo#145]
Hello ! after installing and testing, I see that menu doesn't change when I switch from English to French. 

I miss something?

thanks in advance

**Comment by developer-evan** [comment]
Hello @lupa18 

Thanks for your concern, we added multilingual navigation, please download the latest code and enjoy...

**Comment by lupa18** [comment]
hi @developer-evan ! thanks for your answer. 

I think you missed the anchor language prefix for non-default language. For example each French menu entry, should have something like: 
`pre = "fr/#"`

I hope help with this comment.

**Comment by SoerenGreule** [comment]
> I think you missed the anchor language prefix for non-default language.

I am getting this impression, too. The navigations always links to the default language. This is the case on the demo site, too.
As a workaround you can fix it by setting `defaultContentLanguageInSubdir: true` in the config.yaml and then (in the same file) add the language short in front of the pre for each section in the menu. 
E.g. 
```
menu:
   main:
        - name: about
          pre: 'en/#'
          url: about
          weight: 1
        - name: services
          pre: 'en/#'
          url: services
          weight: 2
```
