### ISSUE TITLE
CSS refers to non existant file

### ISSUE THREAD

**Issue by alrayyes** [themefisher/meghna-hugo#54]
In file https://github.com/themefisher/meghna-hugo/blob/master/assets/css/style.css:

```css
#twitter-feed {
  background-image: url("../images/parallax/twitter.jpg");
  padding-bottom: 100px;
  padding-top: 80px;
}
```
Could be wrong but as far as I can see twitter.jpg is non existant.
